# Generated by Django 6.1.1 on 2026-09-19 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_loginattempt_ledgerentry_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='category',
            field=models.CharField(choices=[('CCTV', 'CCTV / Video'), ('MOBILE', 'Mobile Device Dump'), ('DISK', 'Hard Disk Image'), ('USB', 'Removable Media'), ('LOG', 'System / Access Log'), ('IMAGE', 'Photograph'), ('DOC', 'Document'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='seal_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sealed_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sensitivity',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential'), ('TOP_SECRET', 'Top Secret')], default='RESTRICTED', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='warrant_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open Investigation'), ('IN_COURT', 'In Trial'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('prosecutor', models.CharField(blank=True, max_length=150)),
                ('court_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
