# Generated by Django 5.2.10 on 2026-09-20 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_evidence_category_evidence_seal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='senior_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('CONSTABLE', 'Constable'), ('SUB_INSPECTOR', 'Sub-Inspector'), ('INSPECTOR', 'Inspector'), ('DSP', 'Deputy Superintendent'), ('ADMIN_RANK', 'Administrator')], default='CONSTABLE', max_length=20),
        ),
    ]
