# Generated by Django 6.1.1 on 2026-09-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_case_senior_officer_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='action',
            field=models.CharField(choices=[('INGEST', 'Evidence Ingested'), ('VIEW', 'Record Viewed'), ('DOWNLOAD', 'File Downloaded'), ('TRANSFER', 'Custody Transferred'), ('VERIFY', 'Integrity Verified'), ('VERIFY_EXTERNAL', 'External Verification'), ('TAMPER_ALERT', 'TAMPER DETECTED'), ('CASE_ASSIGNED', 'Case Officer Assigned'), ('CASE_UPDATED', 'Case Updated')], max_length=30),
        ),
    ]
