# Generated by Django 6.1.1 on 2026-09-20 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_alter_ledgerentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='closing_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='custody_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='final_custody',
            field=models.CharField(blank=True, choices=[('ARCHIVE', 'Retained in Case Archive'), ('EVIDENCE_ROOM', 'Retained in Evidence Room'), ('COURT', 'Submitted to Court'), ('RETURNED', 'Returned to Owner'), ('APPELLATE', 'Transferred to Appellate Authority'), ('DESTROYED', 'Destroyed per Court Order')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='action',
            field=models.CharField(choices=[('INGEST', 'Evidence Ingested'), ('VIEW', 'Record Viewed'), ('DOWNLOAD', 'File Downloaded'), ('TRANSFER', 'Custody Transferred'), ('VERIFY', 'Integrity Verified'), ('VERIFY_EXTERNAL', 'External Verification'), ('TAMPER_ALERT', 'TAMPER DETECTED'), ('CASE_ASSIGNED', 'Case Officer Assigned'), ('CASE_UPDATED', 'Case Updated'), ('CASE_CLOSED', 'Case Closed')], max_length=30),
        ),
    ]
