# Generated by Django 6.1.1 on 2026-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_alter_user_rank_alter_user_role_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('CONSTABLE', 'Constable'), ('SUB_INSPECTOR', 'Sub-Inspector'), ('INSPECTOR', 'Inspector'), ('DSP', 'Deputy Superintendent'), ('JR_ANALYST', 'Junior Analyst'), ('ANALYST', 'Analyst'), ('SR_ANALYST', 'Senior Analyst'), ('CHIEF_FORENSIC', 'Chief Forensic Officer'), ('ADMIN_RANK', 'Administrator')], default='', max_length=20),
        ),
    ]
