# Generated by Django 5.2.10 on 2026-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_alter_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True),
        ),
    ]
