# Generated by Django 5.2.10 on 2026-09-20 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_ledgerentry_signature_user_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='action',
            field=models.CharField(choices=[('INGEST', 'Evidence Ingested'), ('VIEW', 'Record Viewed'), ('DOWNLOAD', 'File Downloaded'), ('TRANSFER', 'Custody Transferred'), ('VERIFY', 'Integrity Verified'), ('VERIFY_EXTERNAL', 'External Verification'), ('TAMPER_ALERT', 'TAMPER DETECTED'), ('CASE_ASSIGNED', 'Case Officer Assigned'), ('CASE_UPDATED', 'Case Updated'), ('CASE_CLOSED', 'Case Closed'), ('TRANSFER_INITIATED', 'Transfer Initiated (awaiting co-sign)'), ('TRANSFER_ACCEPTED', 'Transfer Accepted (co-signed)'), ('TRANSFER_REJECTED', 'Transfer Rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='PendingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Countersignature'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transfers', to='vault.evidence')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to=settings.AUTH_USER_MODEL)),
                ('initiate_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.ledgerentry')),
                ('resolve_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.ledgerentry')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
