# Generated by Django 5.2.10 on 2026-09-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_alter_ledgerentry_action_pendingtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='warrant_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
