# Generated by Django 6.1.1 on 2026-09-20 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_ledgerentry_warrant_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_sealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sealed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='merkle_root',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='action',
            field=models.CharField(choices=[('INGEST', 'Evidence Ingested'), ('VIEW', 'Record Viewed'), ('DOWNLOAD', 'File Downloaded'), ('TRANSFER', 'Custody Transferred'), ('VERIFY', 'Integrity Verified'), ('VERIFY_EXTERNAL', 'External Verification'), ('TAMPER_ALERT', 'TAMPER DETECTED'), ('CASE_ASSIGNED', 'Case Officer Assigned'), ('CASE_UPDATED', 'Case Updated'), ('CASE_CLOSED', 'Case Closed'), ('TRANSFER_INITIATED', 'Transfer Initiated (awaiting co-sign)'), ('TRANSFER_ACCEPTED', 'Transfer Accepted (co-signed)'), ('TRANSFER_REJECTED', 'Transfer Rejected'), ('CASE_SEALED', 'Case Sealed (Merkle batch)')], max_length=30),
        ),
    ]
