# Generated by Django 6.1.1 on 2026-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_case_case_sealed_at_case_case_sealed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='warrant_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
